/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PokemonsIndexRouteImport } from './routes/pokemons/index'
import { Route as PokemonsIdRouteImport } from './routes/pokemons/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonsIndexRoute = PokemonsIndexRouteImport.update({
  id: '/pokemons/',
  path: '/pokemons/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonsIdRoute = PokemonsIdRouteImport.update({
  id: '/pokemons/$id',
  path: '/pokemons/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokemons/$id': typeof PokemonsIdRoute
  '/pokemons/': typeof PokemonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokemons/$id': typeof PokemonsIdRoute
  '/pokemons': typeof PokemonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pokemons/$id': typeof PokemonsIdRoute
  '/pokemons/': typeof PokemonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pokemons/$id' | '/pokemons/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokemons/$id' | '/pokemons'
  id: '__root__' | '/' | '/pokemons/$id' | '/pokemons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokemonsIdRoute: typeof PokemonsIdRoute
  PokemonsIndexRoute: typeof PokemonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemons/': {
      id: '/pokemons/'
      path: '/pokemons'
      fullPath: '/pokemons/'
      preLoaderRoute: typeof PokemonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemons/$id': {
      id: '/pokemons/$id'
      path: '/pokemons/$id'
      fullPath: '/pokemons/$id'
      preLoaderRoute: typeof PokemonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokemonsIdRoute: PokemonsIdRoute,
  PokemonsIndexRoute: PokemonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
